/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lovelyswallow.likejava8.util;

import static org.junit.Assert.*;

import org.junit.Test;

public class StringJoinerTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("aa"==null);
    }
}
